name: Daily Task

on:
  schedule:
    - cron: '05 20 * * *' # Codziennie o 12:00 UTC
  workflow_dispatch:

jobs:

  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Remove files in zdjecia directory
        run: rm -rf photo/*

      - name: Download dependencies
        run: npm install

      - name: Write Google JSON to file
        run: echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT }}" | sed 's/\\\\n/\/g' > google.json

      - name: Set GOOGLE_APPLICATION_CREDENTIALS
        env:
          GOOGLE_APPLICATION_CREDENTIALS: google.json
        run: echo "Environment variable set"

      - name: Display JSON file (optional, for debugging)
        run: cat google.json

      - name: Run script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: google.json
        run: node script.js