name: Daily Task

on:
  schedule:
    - cron: '38 12 * * *' 
  workflow_dispatch:

jobs:

  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Remove files in photo directory
        run: rm -rf photo/*

      - name: Download dependencies
        run: npm install

      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "google.json"
          json: ${{ secrets.GOOGLE }}

      - name: Run script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: google.json
        run: node script.js
