name: Daily Task

on:
  schedule:
    - cron: '05 20 * * *' # Codziennie o 12:00 UTC
  workflow_dispatch:

jobs:

  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Remove files in zdjecia directory
        run: rm -rf photo/*

      - name: Install npm dependencies
        run: npm install

      - name: Create google.json file
        run: echo "${{ secrets.GOOGLE }}" > google.json

      - name: debug
        run: ls

      - name: debug
        run: cat google.json

      - name: Run script.js
        run: node script.js
